### ISSUE TITLE
API Link is broken.

### ISSUE THREAD

**Issue by jthomas** [IBM-Bluemix-Docs/cloud-monitoring#1]
https://github.com/IBM-Bluemix-Docs/cloud-monitoring/blob/master/send-metrics/send_data_api.md#sending-data-to-the-monitoring-service

In this section, redirects to....
https://console.bluemix.net/apidocs/927-ibm-cloud-monitoring-rest-api?&language=node#introduction

**Comment by lopezdsr** [comment]
Thank you - I have fixed it now.

**Comment by kkomp** [comment]
Please re-open this issue - Metrics API link is still broken
